editAreaLoader.load_syntax["genero"] = {
    'COMMENT_SINGLE' : {1: "--", 2: "#"}, 
    'COMMENT_MULTI' : {"{": "}"}, 
    'QUOTEMARKS' : {0: "\'", 1: "\""}, 
    'KEYWORDS' : {
        'keywordgroup1': ["ABSOLUTE", "ACCEPT", "ACTION", "ADD", "AFTER", "ALL", "ALTER", "AND", "ANY", "APPEND", "APPLICATION", "AS", "AT", "ATTRIBUTE", "ATTRIBUTES", "AUDIT", "AVG", "BEFORE", "BEGIN", "BETWEEN", "BORDER", "BOTTOM", "BREAKPOINT", "BUFFER", "BUFFERED", "BY", "CALL", "CANCEL", "CASE", "CENTURY", "CHANGE", "CHECK", "CLEAR", "CLIPPED", "CLOSE", "CLUSTER", "COLUMN", "COLUMNS", "COMMAND", "COMMENT", "COMMIT", "COMMITTED", "CONCURRENT ", "CONNECT", "CONNECTION", "CONSTANT", "CONSTRAINED", "CONSTRAINT", "CONSTRUCT", "CONTINUE", "CONTROL", "COUNT", "CREATE", "CROSS", "CURRENT", "DATABASE", "DBA", "DEC", "DECLARE", "DEFAULT", "DEFAULTS", "DEFER", "DEFINE", "DELETE", "DELIMITER", "DESCRIBE", "DESTINATION", "DIM", "DIALOG", "DIMENSION", "DIRTY", "DISCONNECT", "DISPLAY", "DISTINCT", "DORMANT", "DOWN", "DROP", "DYNAMIC", "ELSE", "END", "ERROR", "ESCAPE", "EVERY", "EXCLUSIVE", "EXECUTE", "EXISTS", "EXIT", "EXPLAIN", "EXTEND", "EXTENT", "EXTERNAL", "FETCH", "FGL_DRAWBOX", "FIELD", "FIELD_TOUCHED", "FILE", "FILL", "FINISH", "FIRST", "FLOAT", "FLUSH", "FOR", "FOREACH", "FORM", "FORMAT", "FOUND", "FRACTION", "FREE", "FROM", "FULL", "FUNCTION", "GET_FLDBUF", "GLOBALS", "GO", "GOTO", "GRANT", "GROUP", "HAVING", "HEADER", "HELP", "HIDE", "HOLD", "HOUR", "IDLE", "IF", "IMAGE", "IMMEDIATE", "IN", "INDEX", "INFIELD", "INITIALIZE", "INNER", "INPUT", "INSERT", "INTERRUPT", "INTERVAL", "INTO", "INVISIBLE", "IS", "ISOLATION", "JOIN", "KEEP", "KEY", "LABEL", "LAST", "LEFT", "LENGTH", "LET", "LIKE", "LINE", "LINENO", "LINES", "LOAD", "LOCATE", "LOCK", "LOG", "LSTR", "MAIN", "MARGIN", "MATCHES", "MAX", "MAXCOUNT", "MDY", "MEMORY", "MENU", "MESSAGE", "MIN", "MINUTE", "MOD", "MODE", "MODIFY", "MONEY", "NAME", "NEED", "NEXT", "NO", "NORMAL", "NOT", "NOTFOUND", "NULL", "NUMERIC", "OF", "ON", "OPEN", "OPTION", "OPTIONS", "OR", "ORDER", "OTHERWISE", "OUTER", "OUTPUT", "PAGE", "PAGENO", "PAUSE", "PERCENT", "PICTURE", "PIPE", "PRECISION", "PREPARE", "PREVIOUS", "PRINT", "PRINTER", "PRINTX", "PRIOR", "PRIVILEGES", "PROCEDURE", "PROGRAM", "PROMPT", "PUBLIC", "PUT", "QUIT", "READ", "REAL", "RECORD", "RECOVER", "RED ", "RELATIVE", "RENAME", "REOPTIMIZATION", "REPEATABLE", "REPORT", "RESOURCE", "RETURN", "RETURNING", "REVERSE", "REVOKE", "RIGHT", "ROLLBACK", "ROLLFORWARD", "ROW", "ROWS", "RUN", "SCHEMA", "SCREEN", "SCROLL", "SECOND", "SELECT", "SERIAL", "SET", "SFMT", "SHARE", "SHIFT", "SHOW", "SIGNAL ", "SIZE", "SKIP", "SLEEP", "SOME", "SPACE", "SPACES", "SQL", "SQLERRMESSAGE", "SQLERROR", "SQLSTATE", "STABILITY", "START", "STATISTICS", "STEP", "STOP", "STYLE", "SUM", "SYNONYM", "TABLE", "TEMP", "TERMINATE", "TEXT", "THEN", "THROUGH", "THRU", "TO", "TODAY", "TOP", "TRAILER", "TRANSACTION ", "UNBUFFERED", "UNCONSTRAINED", "UNDERLINE", "UNION", "UNIQUE", "UNITS", "UNLOAD", "UNLOCK", "UP", "UPDATE", "USE", "USER", "USING", "VALIDATE", "VALUE", "VALUES", "VARCHAR", "VIEW", "WAIT", "WAITING", "WARNING", "WHEN", "WHENEVER", "WHERE", "WHILE", "WINDOW", "WITH", "WITHOUT", "WORDWRAP", "WORK", "WRAP"],
        'keywordgroup2': ["&amp;IFDEF", "&amp;ENDIF"],
        'keywordgroup3': ["ARRAY", "BYTE", "CHAR", "CHARACTER", "CURSOR", "DATE", "DATETIME", "DECIMAL", "DOUBLE", "FALSE", "INT", "INTEGER", "SMALLFLOAT", "SMALLINT", "STRING", "TIME", "TRUE"],
        'keywordgroup4': ["BLACK", "BLINK", "BLUE", "BOLD", "ANSI", "ASC", "ASCENDING", "ASCII", "CYAN", "DESC", "DESCENDING", "GREEN", "MAGENTA", "OFF", "WHITE", "YELLOW", "YEAR", "DAY", "MONTH", "WEEKDAY"]
}, 
    'OPERATORS' : ["+", "-", "*", "?", "=", "/", "%", ">", "<", "^", "!", "|", ":"], 
    'DELIMITERS' : [ '(', ')', '[', ']', '{', '}' ], 
    'STYLES' : { 
        'COMMENTS' : 'color: #008080;', 
        'QUOTESMARKS' : 'color: #808080;', 
        'KEYWORDS' : { 
        'keywordgroup1': 'color: #0600FF;',
        'keywordgroup2': 'color: #0000FF;',
        'keywordgroup3': 'color: #008000;',
        'keywordgroup4': 'color: #FF0000;'    }, 
       'OPERATORS' : 'color: #008000;', 
        'DELIMITERS' : 'color: #008000;' 
    } 
}; 
