editAreaLoader.load_syntax["gnuplot"] = {
    'COMMENT_SINGLE' : {1: "#"}, 
    'COMMENT_MULTI' : {}, 
    'QUOTEMARKS' : {0: "`", 1: "\"", 2: "\'"}, 
    'KEYWORDS' : {
        'keywordgroup1': ["bind", "call", "cd", "clear", "exit", "fit", "help", "history", "if", "load", "lower", "pause", "plot", "print", "pwd", "quit", "raise", "replot", "reread", "reset", "save", "set", "shell", "show", "splot", "system", "test", "unset", "update"],
        'keywordgroup2': ["angles", "arrow", "autoscale", "bars", "bmargin", "border", "boxwidth", "cbdata", "cbdtics", "cblabel", "cbmtics", "cbrange", "cbtics", "clabel", "clip", "cntrparam", "colorbox", "contour", "datafile", "date_specifiers", "decimalsign", "dgrid3d", "dummy", "encoding", "fontpath", "format", "grid", "hidden3d", "historysize", "isosamples", "key", "label", "lmargin", "loadpath", "locale", "log", "logscale", "macros", "mapping", "margin", "missing", "mouse", "multiplot", "mx2tics", "mxtics", "my2tics", "mytics", "mztics", "object", "offsets", "origin", "output", "palette", "parametric", "pm3d", "pointsize", "polar", "rmargin", "rrange", "samples", "size", "style", "surface", "table", "term", "terminal", "termoption", "tics", "ticscale", "ticslevel", "time_specifiers", "timefmt", "timestamp", "title", "trange", "urange", "view", "vrange", "x2data", "x2dtics", "x2label", "x2mtics", "x2range", "x2tics", "x2zeroaxis", "xdata", "xdtics", "xlabel", "xmtics", "xrange", "xtics", "xyplane", "xzeroaxis", "y2data", "y2dtics", "y2label", "y2mtics", "y2range", "y2tics", "y2zeroaxis", "ydata", "ydtics", "ylabel", "ymtics", "yrange", "ytics", "yzeroaxis", "zdata", "zdtics", "zero", "zeroaxis", "zlabel", "zmtics", "zrange", "ztics", "zzeroaxis", "noangles", "noarrow", "noautoscale", "nobars", "nobmargin", "noborder", "noboxwidth", "nocbdata", "nocbdtics", "nocblabel", "nocbmtics", "nocbrange", "nocbtics", "noclabel", "noclip", "nocntrparam", "nocolorbox", "nocontour", "nodatafile", "nodate_specifiers", "nodecimalsign", "nodgrid3d", "nodummy", "noencoding", "nofit", "nofontpath", "noformat", "nogrid", "nohidden3d", "nohistorysize", "noisosamples", "nokey", "nolabel", "nolmargin", "noloadpath", "nolocale", "nolog", "nologscale", "nomacros", "nomapping", "nomargin", "nomissing", "nomouse", "nomultiplot", "nomx2tics", "nomxtics", "nomy2tics", "nomytics", "nomztics", "noobject", "nooffsets", "noorigin", "nooutput", "nopalette", "noparametric", "nopm3d", "nopointsize", "nopolar", "noprint", "normargin", "norrange", "nosamples", "nosize", "nostyle", "nosurface", "notable", "noterm", "noterminal", "notermoption", "notics", "noticscale", "noticslevel", "notime_specifiers", "notimefmt", "notimestamp", "notitle", "notmargin", "notrange", "nourange", "noview", "novrange", "nox2data", "nox2dtics", "nox2label", "nox2mtics", "nox2range", "nox2tics", "nox2zeroaxis", "noxdata", "noxdtics", "noxlabel", "noxmtics", "noxrange", "noxtics", "noxyplane", "noxzeroaxis", "noy2data", "noy2dtics", "noy2label", "noy2mtics", "noy2range", "noy2tics", "noy2zeroaxis", "noydata", "noydtics", "noylabel", "noymtics", "noyrange", "noytics", "noyzeroaxis", "nozdata", "nozdtics", "nozero", "nozeroaxis", "nozlabel", "nozmtics", "nozrange", "noztics", "nozzeroaxis"],
        'keywordgroup3': ["pi", "NaN", "GNUTERM", "GPVAL_X_MIN", "GPVAL_X_MAX", "GPVAL_Y_MIN", "GPVAL_Y_MAX", "GPVAL_TERM", "GPVAL_TERMOPTIONS", "GPVAL_OUTPUT", "GPVAL_VERSION", "GPVAL_PATcHLEVEL", "GPVAL_COMPILE_OPTIONS", "MOUSE_KEY", "MOUSE_X", "MOUSE_X2", "MOUSE_Y", "MOUSE_Y2", "MOUSE_BUTTON", "MOUSE_SHIFT", "MOUSE_ALT", "MOUSE_CTRL"],
        'keywordgroup4': ["abs", "acos", "acosh", "arg", "asin", "asinh", "atan", "atan2", "atanh", "besj0", "besj1", "besy0", "besy1", "ceil", "column", "cos", "cosh", "defined", "erf", "erfc", "exists", "exp", "floor", "gamma", "gprintf", "ibeta", "igamma", "imag", "int", "inverf", "invnorm", "lambertw", "lgamma", "log10", "norm", "rand", "random", "real", "sgn", "sin", "sinh", "sprintf", "sqrt", "stringcolumn", "strlen", "strstrt", "substr", "tan", "tanh", "timecolumn", "tm_hour", "tm_mday", "tm_min", "tm_mon", "tm_sec", "tm_wday", "tm_yday", "tm_year", "valid", "word", "words"],
        'keywordgroup5': ["autofreq", "x", "y", "z", "lt", "linetype", "lw", "linewidth", "ls", "linestyle", "out", "rotate by", "screen", "enhanced", "via", "on", "off", "default", "inside", "outside", "tmargin", "at", "left", "right", "center", "top", "bottom", "vertical", "horizontal", "Left", "Right", "noreverse", "reverse", "noinvert", "invert", "samplen", "spacing", "width", "height", "noautotitle", "autotitle", "noenhanced", "nobox", "box", "landscape", "portrait", "eps", "defaultplex", "simplex", "duplex", "fontfile", "add", "delete", "nofontfiles", "level1", "leveldefault", "color", "colour", "monochrome", "solid", "dashed", "dashlength", "dl", "rounded", "butt", "palfuncparam", "blacktext", "colortext", "colourtext", "font", "notransparent", "transparent", "nointerlace", "interlace", "notruecolor", "truecolor", "tiny", "small", "medium", "large", "giant", "nocrop", "crop", "acsplines", "bezier", "binary", "csplines", "every", "example", "frequency", "index", "matrix", "ranges", "sbezier", "smooth", "special-filenames", "thru", "unique", "using", "with", "boxerrorbars", "boxes", "boxxyerrorbars", "candlesticks", "dots", "errorbars", "errorlines", "filledcurves", "financebars", "fsteps", "histeps", "histograms", "image", "impulses", "labels", "lines", "linespoints", "points", "rgbimage", "steps", "vectors", "xerrorbars", "xerrorlines", "xyerrorbars", "xyerrorlines", "yerrorbars", "yerrorlines", "aed512", "aed767", "aifm", "bitgraph", "cgm", "corel", "dumb", "dxf", "eepic", "emf", "emtex", "epslatex", "epson-180dpi", "epson-60dpi", "epson-lx800", "fig", "gif", "gpic", "hp2623a", "hp2648", "hp500c", "hpdj", "hpgl", "hpljii", "hppj", "imagen", "jpeg", "kc-tek40xx", "km-tek40xx", "latex", "mf", "mif", "mp", "nec-cp6", "okidata", "pbm", "pcl5", "png", "pop", "postscript", "pslatex", "pstex", "pstricks", "push", "qms", "regis", "selanar", "starc", "svg", "tandy-60dpi", "tek40xx", "tek410x", "texdraw", "tgif", "tkcanvas", "tpic", "vttek", "x11", "xlib"]
}, 
    'OPERATORS' : ["-", "+", "~", "!", "$", "*", "/", "%", "=", "<", ">", "&", "^", "|", ".", "eq", "ne", "?:", ":", "`", ","], 
    'DELIMITERS' : [ '(', ')', '[', ']', '{', '}' ], 
    'STYLES' : { 
        'COMMENTS' : 'color: #adadad;', 
        'QUOTESMARKS' : 'color: #0000ff;', 
        'KEYWORDS' : { 
        'keywordgroup1': 'color: #b1b100;',
        'keywordgroup2': 'color: #990000;',
        'keywordgroup3': 'color: #550000;',
        'keywordgroup4': 'color: #7a0874;',
        'keywordgroup5': 'color: #448888;'    }, 
       'OPERATORS' : 'color: #000;', 
        'DELIMITERS' : 'color: #000;' 
    } 
}; 
