editAreaLoader.load_syntax["mysql"] = {
    'COMMENT_SINGLE' : {1: "-- ", 2: "#"}, 
    'COMMENT_MULTI' : {"/*": "*/"}, 
    'QUOTEMARKS' : {0: "\'", 1: "\"", 2: "`"}, 
    'KEYWORDS' : {
        'keywordgroup1': ["ACTION", "ADD", "AFTER", "ALGORITHM", "ALL", "ALTER", "ANALYZE", "ANY", "ASC", "AS", "BDB", "BEGIN", "BERKELEYDB", "BINARY", "BTREE", "CALL", "CASCADED", "CASCADE", "CHAIN", "CHECK", "COLUMNS", "COLUMN", "COMMENT", "COMMIT", "COMMITTED", "CONSTRAINT", "CONTAINS SQL", "CONSISTENT", "CONVERT", "CREATE", "CROSS", "DATA", "DATABASES", "DECLARE", "DEFINER", "DELAYED", "DELETE", "DESCRIBE", "DESC", "DETERMINISTIC", "DISABLE", "DISCARD", "DISTINCTROW", "DISTINCT", "DO", "DROP", "DUMPFILE", "DUPLICATE KEY", "ENABLE", "ENCLOSED BY", "ENGINE", "ERRORS", "ESCAPED BY", "EXISTS", "EXPLAIN", "EXTENDED", "FIELDS", "FIRST", "FOR EACH ROW", "FORCE", "FOREIGN KEY", "FROM", "FULL", "FUNCTION", "GLOBAL", "GRANT", "GROUP BY", "HANDLER", "HASH", "HAVING", "HELP", "HIGH_PRIORITY", "IF NOT EXISTS", "IGNORE", "IMPORT", "INDEX", "INFILE", "INNER", "INNODB", "INOUT", "INTO", "INVOKER", "ISOLATION LEVEL", "JOIN", "KEYS", "KEY", "KILL", "LANGUAGE SQL", "LAST", "LIMIT", "LINES", "LOAD", "LOCAL", "LOCK", "LOW_PRIORITY", "MASTER_SERVER_ID", "MATCH", "MERGE", "MIDDLEINT", "MODIFIES SQL DATA", "MODIFY", "MRG_MYISAM", "NATURAL", "NEXT", "NO SQL", "NO", "ON", "OPTIMIZE", "OPTIONALLY", "OPTION", "ORDER BY", "OUTER", "OUTFILE", "OUT", "PARTIAL", "PREV", "PRIMARY KEY", "PRIVILEGES", "PROCEDURE", "PURGE", "QUICK", "READS SQL DATA", "READ", "REFERENCES", "RELEASE", "RENAME", "REPEATABLE", "REQUIRE", "RESTRICT", "RETURNS", "REVOKE", "ROLLBACK", "ROUTINE", "RTREE", "SAVEPOINT", "SELECT", "SERIALIZABLE", "SESSION", "SET", "SHARE MODE", "SHOW", "SIMPLE", "SNAPSHOT", "SOME", "SONAME", "SQL SECURITY", "SQL_BIG_RESULT", "SQL_BUFFER_RESULT", "SQL_CACHE", "SQL_CALC_FOUND_ROWS", "SQL_NO_CACHE", "SQL_SMALL_RESULT", "SSL", "START", "STARTING BY", "STATUS", "STRAIGHT_JOIN", "STRIPED", "TABLESPACE", "TABLES", "TABLE", "TEMPORARY", "TEMPTABLE", "TERMINATED BY", "TO", "TRANSACTIONS", "TRANSACTION", "TRIGGER", "TYPES", "TYPE", "UNCOMMITTED", "UNDEFINED", "UNION", "UNLOCK_TABLES", "UPDATE", "USAGE", "USE", "USER_RESOURCES", "USING", "VALUES", "VALUE", "VIEW", "WARNINGS", "WHERE", "WITH ROLLUP", "WITH", "WORK", "WRITE"],
        'keywordgroup2': ["CURRENT_USER", "DATABASE", "IN", "INSERT", "DEFAULT", "REPLACE", "SCHEMA", "TRUNCATE"],
        'keywordgroup3': ["FALSE", "NULL", "TRUE"],
        'keywordgroup4': ["BIGINT", "BIT", "BLOB", "BOOLEAN", "BOOL", "CHARACTER VARYING", "CHAR VARYING", "DATETIME", "DECIMAL", "DEC", "DOUBLE PRECISION", "DOUBLE", "ENUM", "FIXED", "FLOAT", "GEOMETRYCOLLECTION", "GEOMETRY", "INTEGER", "INT", "LINESTRING", "LONGBLOB", "LONGTEXT", "MEDIUMBLOB", "MEDIUMINT", "MEDIUMTEXT", "MULTIPOINT", "MULTILINESTRING", "MULTIPOLYGON", "NATIONAL CHARACTER", "NATIONAL CHARACTER VARYING", "NATIONAL CHAR VARYING", "NATIONAL VARCHAR", "NCHAR VARCHAR", "NCHAR", "NUMERIC", "POINT", "POLYGON", "REAL", "SERIAL", "SMALLINT", "TEXT", "TIMESTAMP", "TINYBLOB", "TINYINT", "TINYTEXT", "VARBINARY", "VARCHARACTER", "VARCHAR"],
        'keywordgroup5': ["CHAR", "DATE", "TIME"],
        'keywordgroup6': ["AUTO_INCREMENT", "AVG_ROW_LENGTH", "BOTH", "CHECKSUM", "CONNECTION", "DATA DIRECTORY", "DEFAULT NULL", "DELAY_KEY_WRITE", "FULLTEXT", "INDEX DIRECTORY", "INSERT_METHOD", "LEADING", "MAX_ROWS", "MIN_ROWS", "NOT NULL", "PACK_KEYS", "ROW_FORMAT", "SERIAL DEFAULT VALUE", "SIGNED", "SPATIAL", "TRAILING", "UNIQUE", "UNSIGNED", "ZEROFILL"],
        'keywordgroup7': ["CHARSET"],
        'keywordgroup8': ["DAY_HOUR", "DAY_MICROSECOND", "DAY_MINUTE", "DAY_SECOND", "HOUR_MICROSECOND", "HOUR_MINUTE", "HOUR_SECOND", "MINUTE_MICROSECOND", "MINUTE_SECOND", "SECOND_MICROSECOND", "YEAR_MONTH"],
        'keywordgroup9': ["DAY", "HOUR", "MICROSECOND", "MINUTE", "MONTH", "QUARTER", "SECOND", "WEEK", "YEAR"],
        'keywordgroup10': ["AND", "BETWEEN", "CHARACTER SET", "COLLATE", "DIV", "IS NOT NULL", "IS NOT", "IS NULL", "IS", "LIKE", "NOT", "OFFSET", "OR", "REGEXP", "RLIKE", "SOUNDS LIKE", "XOR"],
        'keywordgroup11': ["INTERVAL"],
        'keywordgroup12': ["CASE", "ELSE", "END", "IFNULL", "IF", "NULLIF", "THEN", "WHEN"],
        'keywordgroup13': ["ASCII", "BIN", "BIT_LENGTH", "CHAR_LENGTH", "CHARACTER_LENGTH", "CONCAT_WS", "CONCAT", "ELT", "EXPORT_SET", "FIELD", "FIND_IN_SET", "FORMAT", "HEX", "INSTR", "LCASE", "LEFT", "LENGTH", "LOAD_FILE", "LOCATE", "LOWER", "LPAD", "LTRIM", "MAKE_SET", "MID", "OCTET_LENGTH", "ORD", "POSITION", "QUOTE", "REPEAT", "REVERSE", "RIGHT", "RPAD", "RTRIM", "SOUNDEX", "SPACE", "STRCMP", "SUBSTRING_INDEX", "SUBSTRING", "TRIM", "UCASE", "UNHEX", "UPPER"],
        'keywordgroup14': ["INSERT", "REPLACE", "CHAR"],
        'keywordgroup15': ["ABS", "ACOS", "ASIN", "ATAN2", "ATAN", "CEILING", "CEIL", "CONV", "COS", "COT", "CRC32", "DEGREES", "EXP", "FLOOR", "LN", "LOG10", "LOG2", "LOG", "MOD", "OCT", "PI", "POWER", "POW", "RADIANS", "RAND", "ROUND", "SIGN", "SIN", "SQRT", "TAN"],
        'keywordgroup16': ["TRUNCATE"],
        'keywordgroup17': ["ADDDATE", "ADDTIME", "CONVERT_TZ", "CURDATE", "CURRENT_DATE", "CURRENT_TIME", "CURRENT_TIMESTAMP", "CURTIME", "DATE_ADD", "DATE_FORMAT", "DATE_SUB", "DATEDIFF", "DAYNAME", "DAYOFMONTH", "DAYOFWEEK", "DAYOFYEAR", "EXTRACT", "FROM_DAYS", "FROM_UNIXTIME", "GET_FORMAT", "LAST_DAY", "LOCALTIME", "LOCALTIMESTAMP", "MAKEDATE", "MAKETIME", "MONTHNAME", "NOW", "PERIOD_ADD", "PERIOD_DIFF", "SEC_TO_TIME", "STR_TO_DATE", "SUBDATE", "SUBTIME", "SYSDATE", "TIME_FORMAT", "TIME_TO_SEC", "TIMESTAMPADD", "TIMESTAMPDIFF", "TO_DAYS", "UNIX_TIMESTAMP", "UTC_DATE", "UTC_TIME", "UTC_TIMESTAMP", "WEEKDAY", "WEEKOFYEAR", "YEARWEEK"],
        'keywordgroup18': ["DATE", "DAY", "HOUR", "MICROSECOND", "MINUTE", "MONTH", "QUARTER", "SECOND", "TIME", "WEEK", "YEAR"],
        'keywordgroup19': ["COALESCE", "GREATEST", "ISNULL", "LEAST"],
        'keywordgroup20': ["IN", "INTERVAL"],
        'keywordgroup21': ["AES_DECRYPT", "AES_ENCRYPT", "COMPRESS", "DECODE", "DES_DECRYPT", "DES_ENCRYPT", "ENCODE", "ENCRYPT", "MD5", "OLD_PASSWORD", "PASSWORD", "SHA1", "SHA", "UNCOMPRESS", "UNCOMPRESSED_LENGTH"],
        'keywordgroup22': ["AVG", "BIT_AND", "BIT_OR", "BIT_XOR", "COUNT", "GROUP_CONCAT", "MAX", "MIN", "STDDEV_POP", "STDDEV_SAMP", "STDDEV", "STD", "SUM", "VAR_POP", "VAR_SAMP", "VARIANCE"],
        'keywordgroup23': ["BENCHMARK", "COERCIBILITY", "COLLATION", "CONNECTION_ID", "FOUND_ROWS", "LAST_INSERT_ID", "ROW_COUNT", "SESSION_USER", "SYSTEM_USER", "USER", "VERSION"],
        'keywordgroup24': ["CURRENT_USER", "DATABASE", "SCHEMA", "CHARSET"],
        'keywordgroup25': ["ExtractValue", "BIT_COUNT", "GET_LOCK", "INET_ATON", "INET_NTOA", "IS_FREE_LOCK", "IS_USED_LOCK", "MASTER_POS_WAIT", "NAME_CONST", "RELEASE_LOCK", "SLEEP", "UpdateXML", "UUID"],
        'keywordgroup26': ["DEFAULT"],
        'keywordgroup27': ["Area", "AsBinary", "AsText", "AsWKB", "AsWKT", "Boundary", "Buffer", "Centroid", "Contains", "ConvexHull", "Crosses", "Difference", "Dimension", "Disjoint", "Distance", "EndPoint", "Envelope", "Equals", "ExteriorRing", "GLength", "GeomCollFromText", "GeomCollFromWKB", "GeomFromText", "GeomFromWKB", "GeometryCollectionFromText", "GeometryCollectionFromWKB", "GeometryFromText", "GeometryFromWKB", "GeometryN", "GeometryType", "InteriorRingN", "Intersection", "Intersects", "IsClosed", "IsEmpty", "IsRing", "IsSimple", "LineFromText", "LineFromWKB", "LineStringFromText", "LineStringFromWKB", "MBRContains", "MBRDisjoint", "MBREqual", "MBRIntersects", "MBROverlaps", "MBRTouches", "MBRWithin", "MLineFromText", "MLineFromWKB", "MPointFromText", "MPointFromWKB", "MPolyFromText", "MPolyFromWKB", "MultiLineStringFromText", "MultiLineStringFromWKB", "MultiPointFromText", "MultiPointFromWKB", "MultiPolygonFromText", "MultiPolygonFromWKB", "NumGeometries", "NumInteriorRings", "NumPoints", "Overlaps", "PointFromText", "PointFromWKB", "PointN", "PointOnSurface", "PolyFromText", "PolyFromWKB", "PolygonFromText", "PolygonFromWKB", "Related", "SRID", "StartPoint", "SymDifference", "Touches", "Union", "Within", "X", "Y"]
}, 
    'OPERATORS' : ["Array", "Array"], 
    'DELIMITERS' : [ '(', ')', '[', ']', '{', '}' ], 
    'STYLES' : { 
        'COMMENTS' : 'color: #808080;', 
        'QUOTESMARKS' : 'color: #008000;', 
        'KEYWORDS' : { 
        'keywordgroup1': 'color: #990099;',
        'keywordgroup2': 'color: #990099;',
        'keywordgroup3': 'color: #9900FF;',
        'keywordgroup4': 'color: #999900;',
        'keywordgroup5': 'color: #999900;',
        'keywordgroup6': 'color: #FF9900;',
        'keywordgroup7': 'color: #FF9900;',
        'keywordgroup8': 'color: #9900FF;',
        'keywordgroup9': 'color: #9900FF;',
        'keywordgroup10': 'color: #CC0099;',
        'keywordgroup11': 'color: #CC0099;',
        'keywordgroup12': 'color: #009900;',
        'keywordgroup13': 'color: #000099;',
        'keywordgroup14': 'color: #000099;',
        'keywordgroup15': 'color: #000099;',
        'keywordgroup16': 'color: #000099;',
        'keywordgroup17': 'color: #000099;',
        'keywordgroup18': 'color: #000099;',
        'keywordgroup19': 'color: #000099;',
        'keywordgroup20': 'color: #000099;',
        'keywordgroup21': 'color: #000099;',
        'keywordgroup22': 'color: #000099;',
        'keywordgroup23': 'color: #000099;',
        'keywordgroup24': 'color: #000099;',
        'keywordgroup25': 'color: #000099;',
        'keywordgroup26': 'color: #000099;',
        'keywordgroup27': 'color: #00CC00;'    }, 
       'OPERATORS' : '', 
        'DELIMITERS' : '' 
    } 
}; 
