editAreaLoader.load_syntax["per"] = {
    'COMMENT_SINGLE' : {1: "--", 2: "#"}, 
    'COMMENT_MULTI' : {"{": "}"}, 
    'QUOTEMARKS' : {0: "\'", 1: "\""}, 
    'KEYWORDS' : {
        'keywordgroup1': ["ACCELERATOR", "ACCELERATOR2", "ACTION", "ALT", "AND", "AUTO", "AUTONEXT", "AUTOSCALE", "BETWEEN", "BOTH", "BUTTON", "BUTTONEDIT", "BUTTONTEXTHIDDEN", "BY", "BYTE", "CANVAS", "CENTER", "CHECKBOX", "CLASS", "COLOR", "COLUMNS", "COMBOBOX", "COMMAND", "COMMENT", "COMMENTS", "COMPACT", "COMPRESS", "CONFIG", "CONTROL", "CURRENT", "DATABASE", "DATEEDIT", "DEC", "DEFAULT", "DEFAULTS", "DELIMITERS", "DISPLAY", "DISPLAYONLY", "DOWNSHIFT", "DYNAMIC", "EDIT", "FIXED", "FOLDER", "FONTPITCH", "FORMAT", "FORMONLY", "GRID", "GRIDCHILDRENINPARENT", "GROUP", "HBOX", "HEIGHT", "HIDDEN", "HORIZONTAL", "INCLUDE", "INITIAL", "INITIALIZER", "INPUT", "INSTRUCTIONS", "INTERVAL", "INVISIBLE", "IS", "ITEM", "ITEMS", "JUSTIFY", "KEY", "KEYS", "LABEL", "LEFT", "LIKE", "LINES", "MATCHES", "NAME", "NOENTRY", "NONCOMPRESS", "NORMAL", "NOT", "NOUPDATE", "OPTIONS", "OR", "ORIENTATION", "PACKED", "PAGE", "PICTURE", "PIXELHEIGHT", "PIXELS", "PIXELWIDTH", "POINTS", "PROGRAM", "PROGRESSBAR", "QUERYCLEAR", "QUERYEDITABLE", "RADIOGROUP", "RECORD", "REQUIRED", "REVERSE", "RIGHT", "SAMPLE", "SCREEN", "SCROLL", "SCROLLBARS", "SCROLLGRID", "SECOND", "SEPARATOR", "SHIFT", "SIZE", "SIZEPOLICY", "SMALLFLOAT", "SMALLINT", "SPACING", "STRETCH", "STYLE", "TABINDEX", "TABLE", "TAG", "TEXT", "TEXTEDIT", "THROUGH", "THRU", "TITLE", "TO", "TOOLBAR", "TOPMENU", "TYPE", "UNHIDABLE", "UNHIDABLECOLUMNS", "UNMOVABLE", "UNMOVABLECOLUMNS", "UNSIZABLE", "UNSIZABLECOLUMNS", "UNSORTABLE", "UNSORTABLECOLUMNS", "UPSHIFT", "USER", "VALIDATE", "VALUECHECKED", "VALUEMAX", "VALUEMIN", "VALUEUNCHECKED", "VARCHAR", "VARIABLE", "VBOX", "VERIFY", "VERSION", "VERTICAL", "TIMESTAMP", "WANTCOLUMNSANCHORED", "WANTFIXEDPAGESIZE", "WANTNORETURNS", "WANTTABS", "WHERE", "WIDGET", "WIDTH", "WINDOWSTYLE", "WITHOUT", "WORDWRAP", "X", "Y", "ZEROFILL", "SCHEMA", "ATTRIBUTES", "TABLES", "LAYOUT", "END"],
        'keywordgroup2': ["YEAR", "BLACK", "BLINK", "BLUE", "YELLOW", "WHITE", "UNDERLINE", "CENTURY", "FRACTION", "CHAR", "CHARACTER", "CHARACTERS", "CYAN", "DATE", "DATETIME", "DAY", "DECIMAL", "FALSE", "FLOAT", "GREEN", "HOUR", "INT", "INTEGER", "MAGENTA", "MINUTE", "MONEY", "NONE", "NULL", "REAL", "RED", "TRUE", "TODAY", "MONTH", "IMAGE"]
}, 
    'OPERATORS' : ["+", "-", "*", "?", "=", "/", "%", ">", "<", "^", "!", "|", ":"], 
    'DELIMITERS' : [ '(', ')', '[', ']', '{', '}' ], 
    'STYLES' : { 
        'COMMENTS' : 'color: #008080;', 
        'QUOTESMARKS' : 'color: #808080;', 
        'KEYWORDS' : { 
        'keywordgroup1': 'color: #0600FF;',
        'keywordgroup2': 'color: #0000FF;'    }, 
       'OPERATORS' : 'color: #008000;', 
        'DELIMITERS' : 'color: #008000;' 
    } 
}; 
