tinyMCE.addI18n("en.WPSynHighlight_dlg", {
	desc: 'WP-Synhighlight - format as a source code', 
	WindowTitle: 'CodeSyntax',
	Settings: 'Formatting settings',
	Code: 'Code to paste',
	Language: 'Format as code',
	LineNumbers: 'Line numbers',
	LineNumbersDefault: 'default',
	LineNumbersNo: 'no',
	LineNumbersNormal: 'normal',
	LineNumbersFancy: 'fancy',
	LineNumbersStartWith: 'Start line numbers with',
	Container: 'Use container',
	ContainerDefault: 'default',
	ContainerNone: 'no',
	ContainerDiv: 'DIV',
	ContainerPre: 'PRE',
	ContainerPre_valid: 'PRE valid', 
	ContainerPre_table: 'PRE with table',
	CapitalizeKeywords: 'Change case of keywords',
	CapitalizeKeywordsDefault: 'default',
	CapitalizeKeywordsNo: 'no',
	CapitalizeKeywordsUppercase: 'to uppercase',
	CapitalizeKeywordsLowercase: 'to lowercase',
	TabWidth: 'Tab width',
	StrictMode: 'Strict mode',
	StrictModeDefault: 'default',
	StrictModeNo: 'off',
	StrictModeYes: 'on',
	Title: 'Code box title',
	BookmarkName: 'Bookmark name',
	Insert: 'Insert',
	Cancel: 'Cancel',
	InitialBlockState: 'This code block state when the page is opened',
	InitialBlockStateDefault: 'default',
	InitialBlockStateExpanded: 'expanded',
	InitialBlockStateCollapsed: 'collapsed',
	HighlightLines: 'Highlight lines with these numbers',
	PHPNote: '<b>Note</b>: please always start PHP code from &lt;?php tag to be highlighted correctly.',
	DocLinks: 'Generate documentation links for URLs',
	DocLinksDefault: 'default',
	DocLinksOn: 'yes',
	DocLinksOff: 'no'
});