tinyMCE.addI18n("ru.WPSynHighlight_dlg", {
	desc: 'WP-Synhighlight - отформатировать как исходный код', 
	WindowTitle: 'CodeSyntax',
	Settings: 'Настройки',
	Code: 'Исходный код',
	Language: 'Отформатировать как код',
	LineNumbers: 'Номера строк',
	LineNumbersDefault: 'по умолчанию',
	LineNumbersNo: 'нет',
	LineNumbersNormal: 'обычные',
	LineNumbersFancy: 'необычные',
	LineNumbersStartWith: 'Номера строк начинать с номера',
	Container: 'Использовать контейнер',
	ContainerDefault: 'по умолчанию',
	ContainerNone: 'нет',
	ContainerDiv: 'тег DIV',
	ContainerPre: 'тег PRE',
	ContainerPre_valid: 'тег PRE валидный', 
	ContainerPre_table: 'тег PRE c таблицей',
	CapitalizeKeywords: 'Изменять регистр ключевых слов',
	CapitalizeKeywordsDefault: 'по умолчанию',
	CapitalizeKeywordsNo: 'нет',
	CapitalizeKeywordsUppercase: 'переводить в верхний регистр',
	CapitalizeKeywordsLowercase: 'переводить в нижний регистр',
	TabWidth: 'Ширина табуляции',
	StrictMode: 'Строгий режим работы',
	StrictModeDefault: 'по умолчанию',
	StrictModeNo: 'выключен',
	StrictModeYes: 'включен',
	Title:' Заголовок бокса с кодом',
	BookmarkName: 'Идентификатор закладки',
	Insert: 'Вставить',
	Cancel: 'Отменить',
	InitialBlockState: 'Состояние блока с кодом при открытии страницы',
	InitialBlockStateDefault: 'по умолчанию',
	InitialBlockStateExpanded: 'развернут',
	InitialBlockStateCollapsed: 'свернут',
	HighlightLines: 'Выделить строки c этими номерами',
	PHPNote: '<b>Внимание</b>: начинайте PHP код с тега &lt;?php чтобы он корректно подствечивался Geshi',
	DocLinks: 'Генерировать ссылки на документацию для ключевых слов',
	DocLinksDefault: 'по умолчанию',
	DocLinksOn: 'да',
	DocLinksOff: 'нет'
});